### Lesson 2

#### Number data type

In [2]:
number=round(float(input("Enter the number: ")), 2)
print(number)

5.0

In [4]:
num1=int(input("Enter the 1st number: "))
num2=int(input("Enter the 2nd number: "))
num3=int(input("Enter the 3rd number: "))

print(f"Max number is {max(num1, num2, num3)}")

Max number is 5

In [5]:
km=float(input("Enter in the km: "))

meter=km*1000
centimeter=km*1000000
print(f"Km in meters {meter}")
print(f"Km in centimeters: {centimeter}")

Km in meters 5000.0
Km in centimeters: 5000000.0

In [6]:
num1=int(input("Enter the 1st number: "))
num2=int(input("Enter the 2nd number: "))

quotient=num1//num2
remainder=num1%num2

print(f"Their quotinet is {quotient} and remainder is {remainder}")

Their quotinet is 1 and remainder is 0

In [8]:
celsius=float(input("Enter the temperature in celsius: "))

fahrenheit = (celsius * 9 / 5) + 32

print(f"Temperature is in fahrenheit {fahrenheit}")

Temperature is in fahrenheit 39.2

In [ ]:
number=int(input("Enter the number: "))
print(f"Last digit of the number is {abs(number)%10}")

Last digit of the number is 5

In [11]:
number=int(input("Enter the number"))

print(f"Number is {'even' if number %2==0 else 'odd'}")

Number is even

#### String questions

In [1]:
name=input("Enter yoyr name: ")
birth_year=int(input("Enter the year of your birth: "))
age=2026-birth_year

print(f"{name}, you're {age} years old.")

Sadoqat, you're 21 years old.

In [3]:
txt = 'LMaasleitbtui'
car=txt[1::2]
print(car)

Malibu

In [4]:
text=input("Enter anything you want: ")
length=len(txt)
upper=text.upper()
lower=text.lower()
print(length, upper, lower)

13 AESFUHEFUYH aesfuhefuyh

In [5]:
def palindrome(txt):
    if txt[::-1]==txt:
        return True
    else:
        return False

text=input("Enter anything you want: ")
palindrome(txt)

False

In [9]:
txt=input("Enter the text: ").lower()
vowels=["a", "e", "i", "o", "u"]
count_vowel=0
count_consonant=0
for i in txt:
    if i.isalpha():
        if i in vowels:
           count_vowel+=1
        else:
           count_consonant+=1

print(f"Your text contains {count_vowel} vowels and {count_consonant} consonants.")

Your text contains 1 vowels and 9 consonants.

In [10]:
text1=input("Enter the text: ")
text2=input("Enter the text: ")

print(text2 in text1)

False

In [11]:
sentence=input("Enter the main sentence: ")
replace=input("What should be replaced: ")
with_what=input("What to replace: ")

print(sentence.replace(replace, with_what))

real

In [16]:
txt=input("Enter a string: ")

print(txt[0], txt[-1])

s j

In [19]:
txt=input("Enter a string: ")

print(txt[::-1])

hre

In [21]:
sentence=input("Enter the sentence: ")
words=sentence.split()
print(len(words))

2

In [23]:
txt=input("Enter some text: ")
for i in txt:
    for ch in i:
        if ch.isdigit():
           print(True)

True

In [24]:
words = ["Python", "is", "awesome"]
result = "-".join(words)

In [27]:
txt=input("Enter some text: ")
print(txt.replace(" ", ""))

kmkmnj

In [28]:
txt1=input("Enter: ")
txt2=input("enter: ")
print(txt1==txt2)

False

In [32]:
sentence=input("Enter a sentence: ")

output="".join(i[0].upper() for j in sentence.split())
print(output)

NNN

In [33]:
txt=input("Enter: ")
character=input("Enter a character: ")

print(txt.replace(character, ""))

skrjgn

In [40]:
txt=input("Enter a string: ")
vowels='aeiouAEIUO'
for i in vowels:
    txt=txt.replace(i, "*")
print(txt)

*k**fh

In [42]:
txt=input("Enter a string: ")
start=input("It starts with: ")
end=input('It ends with: ')
print(txt.endswith(start) and txt.startswith(end))

False

#### Boolean

In [43]:
username = input("Enter username: ")
password = input("Enter password: ")

if username and password:
    print("Username and password are valid.")
else:
    print("Username or password cannot be empty.")

Username and password are valid.

In [45]:
a = int(input("Enter first number: "))
b = int(input("Enter second number: "))

if a == b:
    print("The numbers are equal.")
else:
    print("The numbers are not equal.")

The numbers are not equal.

In [46]:
num = int(input("Enter a number: "))

if num > 0 and num % 2 == 0:
    print("The number is positive and even.")
else:
    print("The number is not positive and even.")

The number is positive and even.

In [47]:
a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
c = int(input("Enter third number: "))

if a != b and a != c and b != c:
    print("All numbers are different.")
else:
    print("Some numbers are the same.")

Some numbers are the same.

In [48]:
s1 = input("Enter first string: ")
s2 = input("Enter second string: ")

if len(s1) == len(s2):
    print("Strings have the same length.")
else:
    print("Strings have different lengths.")

Strings have different lengths.

In [49]:
num = int(input("Enter a number: "))

if num % 3 == 0 and num % 5 == 0:
    print("The number is divisible by both 3 and 5.")
else:
    print("The number is not divisible by both 3 and 5.")

The number is not divisible by both 3 and 5.

In [50]:
a = int(input("Enter first number: "))
b = int(input("Enter second number: "))

if a + b > 50:
    print("The sum is greater than 50.")
else:
    print("The sum is not greater than 50.")

The sum is greater than 50.

In [52]:
a = int(input("Enter number: "))


if 10<=a<=20:
    print("Number is in between 10 and 20.")
else:
    print("Number is not in between 10 and 20.")

Number is not in between 10 and 20.

### Lesson 3

#### List, Dictionary, Tuple, Set

In [2]:
#18. **Find Sublist**: Given a list and a sublist, check if the sublist exists within the list.
lst = [1, 2, 2, 3]
sub = [2, 3]
found = any(lst[i:i+len(sub)] == sub for i in range(len(lst)))
print(found)

True

In [8]:
#8. **Remove Element**: Given a set and an element, remove the element if it exists.
s = [1, 2, 2, 3]
x = 2
s.pop(x)
print(s)

[1, 2, 3]

In [4]:
#26. **Get Middle Element**: Given a list, find the middle element. If the list has an even number of elements, return the two middle elements.
mid = len(lst) // 2
print(lst[mid-1:mid+1] if len(lst) % 2 == 0 else lst[mid])

[2, 2]

In [5]:
#29. **Remove Element by Index**: Given a list and an index, remove the element at that index if it exists.
idx = 1
if 0 <= idx < len(lst):
    lst.pop(idx)
print(lst)

[1, 2, 3]

In [9]:
#31. **Repeat Elements**: Given a list and a number, create a new list where each element is repeated that number of times.
n = 3
print([x for x in lst for _ in range(n)])

[1, 1, 1, 2, 2, 2, 3, 3, 3]

In [10]:
#33. **Find All Indices**: Given a list and an element, find all the indices of that element in the list.
x = 2
print([i for i, v in enumerate(lst) if v == x])

[1]

In [11]:
#34. **Rotate List**: Given a list, create a new list that is a rotated version of the original list (shift elements to the right).
k = 1
print(lst[-k:] + lst[:-k])

[3, 1, 2]

In [12]:
#39. **Create Nested List**: Create a new list that contains sublists, where each sublist contains a specified number of elements from the original list.
n = 2
print([lst[i:i+n] for i in range(0, len(lst), n)])

[[1, 2], [3]]

### Lesson 4

In [14]:
def uncommon(list1, list2):
    uncommon=[]

    for x in list1:
        if x not in list2:
            uncommon.append(x)
    
    for x in list2:
        if x not in list1:
            uncommon.append(x)
    
    return uncommon

list1=[1, 2, 3, 4]
list2=[3, 4, 5, 6]

uncommon(list1, list2)

[1, 2, 5, 6]

In [19]:
def square(n):
    for i in range(n):
        print(i**2)

    
n=int(input("Enter the number: "))
square(n)

0
1
4
9

In [7]:
"""
### Bonus Challenge
Task: Create a simple text-based Rock, Paper, Scissors game where the player plays against the computer.
- The computer randomly chooses `rock`, `paper`, or `scissors` using `random.choice()`.
- The player enters their choice.
- Display the winner and keep track of scores for the player and the computer.
- First to 5 points wins the match.

"""
import random
choices=['rock', 'paper', 'scissors']

human_score=0
comp_score=0


while human_score<5 and comp_score<5:
    human_choice = input("Enter your choice (rock, paper, scissors): ").lower()
    comp_choice = random.choice(choices)

    print(f"Computer chose: {comp_choice}")

    if human_choice==comp_choice:
         print("No one won")
    elif human_choice=='paper' and comp_choice=='rock':
         human_score+=1
    elif human_choice=='rock' and comp_choice=='scissors':
         human_score+=1
    elif human_choice=='scissors' and comp_choice=='paper':
        human_score+=1
    else:
        comp_score+=1
    
    print(f"Score -> You: {human_score} | Computer: {comp_score}")
    print("-" * 30)

print("Game over")

Computer chose: scissors
Score -> You: 1 | Computer: 0
------------------------------
Computer chose: scissors
Score -> You: 1 | Computer: 1
------------------------------
Computer chose: paper
Score -> You: 1 | Computer: 2
------------------------------
Computer chose: scissors
Score -> You: 1 | Computer: 3
------------------------------
Computer chose: paper
Score -> You: 2 | Computer: 3
------------------------------
Computer chose: rock
No one won
Score -> You: 2 | Computer: 3
------------------------------
Computer chose: rock
No one won
Score -> You: 2 | Computer: 3
------------------------------
Computer chose: rock
Score -> You: 3 | Computer: 3
------------------------------
Computer chose: paper
Score -> You: 4 | Computer: 3
------------------------------
Computer chose: paper
Score -> You: 4 | Computer: 4
------------------------------
Computer chose: scissors
Score -> You: 4 | Computer: 5
------------------------------
Game over

In [10]:
"""
**3.** `txt` nomli string saqlovchi o'zgaruvchi berilgan. `txt`dagi har uchinchi belgidan
 keyin pastgi chiziqcha (underscore) qo'yilsin. Agar belgi unli harf yoki orqasidan ostki
 chiziqcha qo'yilgan harf bo'lsa, ostki chiziqcha keyingi harfdan keyin qo'yilsin.
 Agar belgi satrdagi oxirgi belgi bo'lsa chiziqcha qo'yilmasin.


input: hello
output: hel_lo

input: assalom
output: ass_alom

input: abcabcdabcdeabcdefabcdefg
output: abc_abcd_abcdeab_cdef_abcdefg

"""

def add_underscore(txt):
    vowels='aeiou'
    count=0
    result=''

    for i in range(len(txt)):
        result+=txt[i]
        count+=1

        if count==3 and i != (len(txt)-1):
            if txt[i] not in vowels:
                result+='_'
                count=0
    return result

txt=input("Enter your string: ")
add_underscore(txt)

'sdj_fnh_su'

In [ ]:
"""
**4. Number Guessing Game**
Create a simple number guessing game.
- The computer randomly selects a number between 1 and 100. 
- If the guess is high, print "Too high!". 
- If the guess is low, print "Too low!". 
- If they guess correctly, print "You guessed it right!" and exit the loop.
- The player has 10 attempts to guess it. If the player can not find the correct number in 10 attempts, print "You lost. Want to play again? ".
- If the player types one of 'Y', 'YES', 'y', 'yes', 'ok' then start the game from the beginning.


> Hint: Use Python’s `random.randint()` to generate the number.
"""
import random

number=random.randint(1, 100)
count=0
while count<10:
    guess=int(input("Enter the guess between 1 and 100: "))
    count+=1
    if guess==number:
        print("You found the number")
        break
    elif guess>number:
        print("Too high")
    elif guess<number:
        print("Too low")
    else:
        print("Incorrect guess")
print(f"You found the number in {count} guesses.")

Too low
Too low
Too high
Too high
Too low
Too low
Too low
Too low
You found the number
You found the number in 9 guesses.

In [14]:
"""
**5. Password Checker**
Task: Create a simple password checker.
- Ask the user to enter a password. 
- If the password is shorter than 8 characters, print "Password is too short." 
- If the password doesn't contain at least one uppercase letter, print "Password must contain an uppercase letter.". 
- If the password meets both criteria, print "Password is strong."

"""

def password_checker(password):
    if len(password)<8:
       print("Password is too short.")
    elif not any(c.isupper() for c in password):
       print("Password must contain an uppercase letter.")
    else:
       print("Password is strong")

password=input("Enter your password: ")
password_checker(password)

Password is strong

In [7]:
"""
**6. Prime Numbers**
Task: Write a Python program that prints all prime numbers between 1 and 100.

> A prime number is a number greater than 1 that is not divisible by any number other than 1 and itself. Use nested loops to check divisibility.

---
"""
def print_primes(limit):
    for num in range(2, limit + 1):

        is_prime = True  # reset for each number

        for i in range(2, int(num ** 0.5) + 1):
            if num % i == 0:
                is_prime = False
                break

        if is_prime:
            print(num)


num = int(input("Till which number of primes you wanna see: "))
print_primes(num)

2
3

### Lesson 5

In [9]:
### Task 1
"""
Write a script called temperature.py that defines two functions:

1. _convert_cel_to_far()_ which takes one float parameter representing degrees Celsius 
and returns a float representing the same temperature in degrees Fahrenheit using the following formula:
   _F = C \* 9/5 + 32_
2. _convert_far_to_cel()_ which take one float parameter representing degrees Fahrenheit
and returns a float representing the same temperature in degrees Celsius using the following formula:
   _C = (F - 32) \* 5/9_

The script should first prompt the user to enter a temperature in degrees Fahrenheit
and then display the temperature converted to Celsius. Then prompt the user to enter a temperature
in degrees Celsius and display the temperature converted to Fahrenheit. All converted temperatures
should be rounded to 2 decimal places.

Enter a temperature in degrees F: 72
72 degrees F = 22.22 degrees C

Enter a temperature in degrees C: 37
37 degrees C = 98.60 degrees F

"""
def convert_cel_to_far(cel):
    far = cel* 9/5 + 32
    return far

def convert_far_to_cel(far):
    cel = (far - 32) * 5/9
    return cel

# Fahrenheit to Celsius
far = float(input("Enter a temperature in degrees F: "))
cel = convert_far_to_cel(far)
print(f"{far} degrees F = {round(cel, 2)} degrees C")

print()  # blank line for formatting

# Celsius to Fahrenheit
cel = float(input("Enter a temperature in degrees C: "))
far = convert_cel_to_far(cel)
print(f"{cel} degrees C = {round(far, 2)} degrees F")

4.0 degrees F = -15.56 degrees C

5.0 degrees C = 41.0 degrees F

#### Task 2

In [11]:
def invest(principal_amount, rate_of_return, num_of_years):
    for year in range(1, num_of_years + 1):
        principal_amount = principal_amount * (1 + rate_of_return)
        print(f"Year {year}: {round(principal_amount, 2)}")


principal_amount = float(input("Enter the principal amount in USD($): "))
rate_of_return = float(input("Enter the rate of return in percentage(%): ")) / 100
num_of_years = int(input("Enter the number of years: "))

invest(principal_amount, rate_of_return, num_of_years)

Year 1: 56.7
Year 2: 59.54
Year 3: 62.51
Year 4: 65.64

#### Task 3

In [ ]:
def factor(number):
    for i in range (1, number+1):
        if number%i==0:
            print(f"{i} is a factor of {number}")

number=int(input("Enter the number: "))
factor(number)

1 is a factor of 12
2 is a factor of 12
3 is a factor of 12
4 is a factor of 12
6 is a factor of 12

#### Task 4

In [ ]:
import math

universities = [
    ['California Institute of Technology', 2175, 37704],
    ['Harvard', 19627, 39849],
    ['Massachusetts Institute of Technology', 10566, 40732],
    ['Princeton', 7802, 37000],
    ['Rice', 5879, 35551],
    ['Stanford', 19535, 40569],
    ['Yale', 11701, 40500]
]

# 1 Extract enrollment and tuition lists
def enrollment_stats(data):
    students = [uni[1] for uni in data]
    tuition = [uni[2] for uni in data]
    return students, tuition


# 2 Mean function
def mean(values):
    return sum(values) / len(values)


# 3 Median function
def median(values):
    sorted_values = sorted(values)
    n = len(sorted_values)
    mid = n // 2
    
    if n % 2 == 0:
        return (sorted_values[mid - 1] + sorted_values[mid]) / 2
    else:
        return sorted_values[mid]


# ---- MAIN LOGIC ----
students, tuition = enrollment_stats(universities)

total_students = sum(students)
total_tuition = sum(tuition)

student_mean = mean(students)
student_median = median(students)

tuition_mean = mean(tuition)
tuition_median = median(tuition)

print('*' * 30)
print(f"Total students: {total_students:,}")
print(f"Total tuition: $ {total_tuition:,}")
print()
print(f"Student mean: {student_mean:,.2f}")
print(f"Student median: {student_median:,}")
print()
print(f"Tuition mean: $ {tuition_mean:,.2f}")
print(f"Tuition median: $ {tuition_median:,}")
print('*' * 30)

******************************
Total students: 77,285
Total tuition: $ 271,905

Student mean: 11,040.71
Student median: 10,566

Tuition mean: $ 38,843.57
Tuition median: $ 39,849
******************************

#### Task 5
Define a function `is_prime(n)` which returns `True` if the given $n$ ($n$ > 0) is _prime number_, otherwise returns `False`.

In [ ]:
def is_prime(number):
    for i in range(2, int(number**0.5)+1):
        if number%i==0:
            return False
        else:
            True
        
is_prime(int(input("Enter your number (n>1): ")))

False

### Lesson 6

In [8]:
def check(func):
    def abc(a, b):
        if b==0:
            return "Denominator can not be zero!"
        return func(a, b)
    return abc

@check
def divide(a, b):
    return a/b

print(divide(6, 2))
print(divide(6, 0))

3.0
Denominator can not be zero!

### Lesson 16

##### Part 1

In [33]:
import pandas as pd

In [34]:
import sqlite3

with sqlite3.connect('data/chinook.db') as f:
    df_customer=pd.read_sql(
        'Select * from customers',
        con=f
    )

In [35]:
df_customer.head(10)

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
1,2,Leonie,Köhler,NaN,Theodor-Heuss-Straße 34,Stuttgart,NaN,Germany,70174,+49 0711 2842222,NaN,leonekohler@surfeu.de,5
2,3,François,Tremblay,NaN,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,+1 (514) 721-4711,NaN,ftremblay@gmail.com,3
3,4,Bjørn,Hansen,NaN,Ullevålsveien 14,Oslo,NaN,Norway,0171,+47 22 44 22 22,NaN,bjorn.hansen@yahoo.no,4
4,5,František,Wichterlová,JetBrains s.r.o.,Klanova 9/506,Prague,NaN,Czech Republic,14700,+420 2 4172 5555,+420 2 4172 5555,frantisekw@jetbrains.com,4
5,6,Helena,Holý,NaN,Rilská 3174/6,Prague,NaN,Czech Republic,14300,+420 2 4177 0449,NaN,hholy@gmail.com,5
6,7,Astrid,Gruber,NaN,"Rotenturmstraße 4, 1010 Innere Stadt",Vienne,NaN,Austria,1010,+43 01 5134505,NaN,astrid.gruber@apple.at,5
7,8,Daan,Peeters,NaN,Grétrystraat 63,Brussels,NaN,Belgium,1000,+32 02 219 03 03,NaN,daan_peeters@apple.be,4
8,9,Kara,Nielsen,NaN,Sønder Boulevard 51,Copenhagen,NaN,Denmark,1720,+453 3331 9991,NaN,kara.nielsen@jubii.dk,4
9,10,Eduardo,Martins,Woodstock Discos,"Rua Dr. Falcão Filho, 155",São Paulo,SP,Brazil,01007-010,+55 (11) 3033-5446,+55 (11) 3033-4564,eduardo@woodstock.com.br,4

In [36]:
df=pd.read_json('data/iris.json')
df

     sepalLength  sepalWidth  petalLength  petalWidth    species
0            5.1         3.5          1.4         0.2     setosa
1            4.9         3.0          1.4         0.2     setosa
2            4.7         3.2          1.3         0.2     setosa
3            4.6         3.1          1.5         0.2     setosa
4            5.0         3.6          1.4         0.2     setosa
..           ...         ...          ...         ...        ...
145          6.7         3.0          5.2         2.3  virginica
146          6.3         2.5          5.0         1.9  virginica
147          6.5         3.0          5.2         2.0  virginica
148          6.2         3.4          5.4         2.3  virginica
149          5.9         3.0          5.1         1.8  virginica

[150 rows x 5 columns]

In [37]:
df.shape

(150, 5)

In [38]:
df.columns.tolist()

['sepalLength', 'sepalWidth', 'petalLength', 'petalWidth', 'species']

In [39]:
df_titanic=pd.read_excel('data/titanic.xlsx')
df_titanic.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [40]:
df_employee=pd.read_csv('data/employee.csv')
df_employee.sample(10)

,UNIQUE_ID,POSITION_TITLE,DEPARTMENT,BASE_SALARY,RACE,EMPLOYMENT_TYPE,GENDER,EMPLOYMENT_STATUS,HIRE_DATE,JOB_DATE
640,640,SURVEILLANCE INVESTIGATOR-EPIDEMIOLOGY,Health & Human Services,47362.0,White,Full Time,Male,Active,2015-12-07,2015-12-07
1619,1619,CAPTAIN,Houston Fire Department (HFD),66523.0,White,Full Time,Male,Active,2001-11-26,2011-05-16
593,593,CITY ATTORNEY,Legal Department,275000.0,Black or African American,Full Time,Male,Active,2016-05-02,2016-05-02
799,799,POLICE SERGEANT,Houston Police Department-HPD,NaN,White,Full Time,Male,Active,1991-11-12,2003-07-10
690,690,ACCOUNTANT ASSOCIATE,Houston Airport System (HAS),39229.0,Black or African American,Full Time,Female,Active,1997-04-26,2010-11-27
1036,1036,FIRE FIGHTER,Houston Fire Department (HFD),57815.0,Hispanic/Latino,Full Time,Male,Active,2001-10-30,2002-11-09
1327,1327,SENIOR REFUSE TRUCK DRIVER,Solid Waste Management,32968.0,Black or African American,Full Time,Male,Active,2009-11-16,2009-11-16
1846,1846,LIBRARY ASSISTANT,Library,26125.0,American Indian or Alaskan Native,Full Time,Female,Active,2008-05-05,2013-01-19
606,606,SENIOR POLICE OFFICER,Houston Police Department-HPD,66614.0,Hispanic/Latino,Full Time,Male,Active,1984-04-02,2004-09-11
336,336,9-1-1 TELECOMMUNICATOR,Houston Emergency Center (HEC),38813.0,Black or African American,Full Time,Female,Active,1989-04-04,2003-06-14

##### Part 2

In [41]:
df.columns = df.columns.str.lower()
type(df)

pandas.DataFrame

In [42]:
df.columns

Index(['sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species'], dtype='str')

In [32]:
df[['sepallength', 'sepalwidth']]

     sepallength  sepalwidth
0            5.1         3.5
1            4.9         3.0
2            4.7         3.2
3            4.6         3.1
4            5.0         3.6
..           ...         ...
145          6.7         3.0
146          6.3         2.5
147          6.5         3.0
148          6.2         3.4
149          5.9         3.0

[150 rows x 2 columns]

In [49]:
df_titanic.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [48]:
df[df_titanic['Age']>30].drop(columns='species')

C:\Users\user\AppData\Local\Temp\ipykernel_10132\2065537426.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[df_titanic['Age']>30].drop(columns='species')

     sepallength  sepalwidth  petallength  petalwidth
1            4.9         3.0          1.4         0.2
3            4.6         3.1          1.5         0.2
4            5.0         3.6          1.4         0.2
6            4.6         3.4          1.4         0.3
11           4.8         3.4          1.6         0.2
13           4.3         3.0          1.1         0.1
15           5.7         4.4          1.5         0.4
18           5.7         3.8          1.7         0.3
20           5.4         3.4          1.7         0.2
21           5.1         3.7          1.5         0.4
25           5.0         3.0          1.6         0.2
30           4.8         3.1          1.6         0.2
33           5.5         4.2          1.4         0.2
35           5.0         3.2          1.2         0.2
40           5.0         3.5          1.3         0.3
52           6.9         3.1          4.9         1.5
54           6.5         2.8          4.6         1.5
61           5.9         3.0          4.2         1.5
62           6.0         2.2          4.0         1.0
70           5.9         3.2          4.8         1.8
74           6.4         2.9          4.3         1.3
85           6.0         3.4          4.5         1.6
92           5.8         2.6          4.0         1.2
94           5.6         2.7          4.2         1.3
96           5.7         2.9          4.2         1.3
98           5.1         2.5          3.0         1.1
99           5.7         2.8          4.1         1.3
103          6.3         2.9          5.6         1.8
104          6.5         3.0          5.8         2.2
108          6.7         2.5          5.8         1.8
110          6.5         3.2          5.1         2.0
116          6.5         3.0          5.5         1.8
122          7.7         2.8          6.7         2.0
123          6.3         2.7          4.9         1.8
124          6.7         3.3          5.7         2.1
129          7.2         3.0          5.8         1.6
130          7.4         2.8          6.1         1.9
132          6.4         2.8          5.6         2.2
137          6.4         3.1          5.5         1.8
148          6.2         3.4          5.4         2.3
149          5.9         3.0          5.1         1.8

In [52]:
from collections import Counter
count_gender=Counter(df_titanic['Sex'])
count_gender

Counter({'male': 577, 'female': 314})

In [59]:
df_movie=pd.read_csv('data/movie.csv')
duration_of=df_movie[df_movie['duration']>120]
duration_of
#df_movie.columns

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
5,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,...,738.0,English,USA,PG-13,263700000.0,2012.0,632.0,6.6,2.35,24000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4674,Color,Kay Pollak,34.0,133.0,10.0,19.0,Frida Hallgren,690.0,9910.0,Comedy|Drama|Music|Romance,...,94.0,Swedish,Sweden,NaN,25000000.0,2004.0,24.0,7.6,1.85,0
4695,Black and White,D.W. Griffith,69.0,123.0,204.0,9.0,Mae Marsh,436.0,NaN,Drama|History|War,...,88.0,NaN,USA,Not Rated,385907.0,1916.0,22.0,8.0,1.33,691
4767,Black and White,King Vidor,48.0,151.0,54.0,6.0,Renée Adorée,81.0,NaN,Drama|Romance|War,...,45.0,NaN,USA,Not Rated,245000.0,1925.0,12.0,8.3,1.33,226
4792,Black and White,Carl Theodor Dreyer,54.0,126.0,147.0,0.0,Sylvia Eckhausen,0.0,NaN,Drama|Fantasy,...,49.0,Danish,Denmark,Not Rated,NaN,1955.0,0.0,8.1,1.37,863
4893,NaN,Brandon Landers,NaN,143.0,8.0,8.0,Alana Kaniewski,720.0,NaN,Drama|Horror|Thriller,...,8.0,English,USA,NaN,17350.0,2011.0,19.0,3.0,NaN,33

In [64]:
likes_asc=df_movie.sort_values(by='director_facebook_likes', ascending=False)
likes_asc

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
3603,Color,Joseph Gordon-Levitt,364.0,90.0,23000.0,694.0,Scarlett Johansson,23000.0,24475193.0,Comedy|Drama|Romance,...,314.0,English,USA,R,3000000.0,2013.0,19000.0,6.6,2.35,33000
66,Color,Christopher Nolan,645.0,152.0,22000.0,11000.0,Heath Ledger,23000.0,533316061.0,Action|Crime|Drama|Thriller,...,4667.0,English,USA,PG-13,185000000.0,2008.0,13000.0,9.0,2.35,37000
1222,Color,Christopher Nolan,341.0,130.0,22000.0,19000.0,Hugh Jackman,23000.0,53082743.0,Drama|Mystery|Sci-Fi|Thriller,...,1100.0,English,USA,PG-13,40000000.0,2006.0,20000.0,8.5,2.35,49000
1057,Color,Christopher Nolan,185.0,118.0,22000.0,319.0,Maura Tierney,14000.0,67263182.0,Drama|Mystery|Thriller,...,651.0,English,USA,R,46000000.0,2002.0,509.0,7.2,2.35,0
96,Color,Christopher Nolan,712.0,169.0,22000.0,6000.0,Anne Hathaway,11000.0,187991439.0,Adventure|Drama|Sci-Fi,...,2725.0,English,USA,PG-13,165000000.0,2014.0,11000.0,8.6,2.35,349000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4683,Color,NaN,75.0,60.0,NaN,833.0,Masi Oka,1000.0,NaN,Drama|Fantasy|Sci-Fi|Thriller,...,379.0,English,USA,TV-14,NaN,NaN,923.0,7.7,16.00,0
4688,Color,NaN,11.0,22.0,NaN,6.0,Ron Lynch,59.0,NaN,Animation|Comedy|Drama,...,82.0,English,USA,TV-PG,NaN,NaN,11.0,8.2,1.33,526
4704,Color,NaN,23.0,43.0,NaN,576.0,Tracy Spiridakos,2000.0,NaN,Action|Adventure|Drama|Sci-Fi,...,323.0,English,USA,TV-14,NaN,NaN,821.0,6.7,16.00,17000
4752,Color,NaN,11.0,58.0,NaN,250.0,James Norton,887.0,NaN,Crime|Drama,...,59.0,English,UK,TV-MA,NaN,NaN,340.0,8.5,16.00,10000
4912,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000

##### Part 3

In [68]:
df.dtypes

sepallength    float64
sepalwidth     float64
petallength    float64
petalwidth     float64
species            str
dtype: object

In [77]:
numeric_df = df.select_dtypes(include='number')

for column in numeric_df.columns:
    print(f"{column}:")
    print(f"  Mean: {numeric_df[column].mean()}")
    print(f"  Median: {numeric_df[column].median()}")
    print(f"  Std Dev: {numeric_df[column].std()}")
    print()

sepallength:
  Mean: 5.843333333333334
  Median: 5.8
  Std Dev: 0.828066127977863

sepalwidth:
  Mean: 3.0573333333333337
  Median: 3.0
  Std Dev: 0.4358662849366982

petallength:
  Mean: 3.7580000000000005
  Median: 4.35
  Std Dev: 1.7652982332594662

petalwidth:
  Mean: 1.1993333333333338
  Median: 1.3
  Std Dev: 0.7622376689603467

In [79]:
print(f"Minimum age is {df_titanic['Age'].min()}")
print(f"Maximum age is {df_titanic['Age'].max()}")
print(f"Sum of ages is {df_titanic['Age'].sum()}")

Minimum age is 0.42
Maximum age is 80.0
Sum of ages is 21205.17

In [ ]:
# Top director
top_director = (df_movie.groupby('director_name')['director_facebook_likes'].sum().idxmax())
print(top_director)

Steven Spielberg

:

In [81]:
# 5 longest movies
longest_movies = (df_movie.nlargest(5, 'duration')[['movie_title', 'duration', 'director_name']])
print(longest_movies)

                   movie_title  duration        director_name
1694                   Trapped     511.0                  NaN
2436                    Carlos     334.0                  NaN
1487       Blood In, Blood Out     330.0      Taylor Hackford
1134             Heaven's Gate     325.0       Michael Cimino
3254  The Legend of Suriyothai     300.0  Chatrichalerm Yukol

### Lesson 17